import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import {
  extractPdfText,
  NotAPdfError,
  EmptyPdfTextError,
} from "../../backend/src/services/pdfImport.js";
import { parseResumeText } from "../../shared/import/parseResumeText.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Generated by fixtures/generate.mjs from the current renderer — rerun that
// script if the renderer's output shape changes and this fixture goes stale.
const FIXTURE_PATH = path.join(__dirname, "fixtures/sample-resume.pdf");

describe("extractPdfText", () => {
  it("extracts readable text from a real resume PDF", async () => {
    const buffer = fs.readFileSync(FIXTURE_PATH);
    const text = await extractPdfText(buffer);
    expect(text).toContain("Aditi Sharma");
    expect(text).toContain("aditi.sharma@example.com");
    expect(text).toContain("EDUCATION");
  });

  it("rejects a non-PDF buffer", async () => {
    await expect(extractPdfText(Buffer.from("not a pdf"))).rejects.toBeInstanceOf(NotAPdfError);
  });

  it("rejects an empty buffer", async () => {
    await expect(extractPdfText(Buffer.alloc(0))).rejects.toBeInstanceOf(NotAPdfError);
  });
});

describe("PDF import pipeline end-to-end", () => {
  it("extracts a full draft from a real generated resume PDF", async () => {
    const buffer = fs.readFileSync(FIXTURE_PATH);
    const text = await extractPdfText(buffer);
    const draft = parseResumeText(text);

    expect(draft.personal.name).toBe("Aditi Sharma");
    expect(draft.personal.email).toBe("aditi.sharma@example.com");
    expect(draft.personal.links.length).toBeGreaterThan(0);
    expect(draft.summary).toContain("backend development");
    expect(draft.skills.length).toBeGreaterThan(0);
    expect(draft.certifications[0]?.name).toContain("AWS Cloud Practitioner");
    // This fixture's bullets carry no glyph (see the note in
    // shared/import/parseResumeText.js), so experience/projects degrade to
    // one entry per line rather than being cleanly grouped — still present,
    // still non-empty, nothing crashes or silently drops the content.
    expect(draft.experience.length).toBeGreaterThan(0);
    expect(draft.projects.length).toBeGreaterThan(0);
  });
});
